name: Push Release

on:
  push:
    branches:
      - production

jobs:
  Build-Plugin-Artifact:
    name: Build_Plugin_Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install
      - run: npm build

      - run: mkdir -p builds/
      - run: zip -r builds/gfetc.zip ./* -x "node_modules/*"

      - uses: actions/upload-artifact@3
        with:
          name: release
          path: builds/gfetc.zip



